### ISSUE TITLE
About pink/purple color removal request

### ISSUE THREAD

**Issue by mbonaci** [birdwing/Brackets-MBO-Theme#3]
Pink/purple:
![image](https://cloud.githubusercontent.com/assets/497926/4270395/a5d5b69a-3cca-11e4-85ff-f0ef13ddae62.png)

This is the cleanest one:
![image](https://cloud.githubusercontent.com/assets/497926/4270413/d6b74f8a-3cca-11e4-9dbe-63b2b01efb9b.png)

This one is not bad, but it's too saturated:
![image](https://cloud.githubusercontent.com/assets/497926/4270426/004b7556-3ccb-11e4-8fd5-81c284784e7e.png)

And this one is the worst of all four:
![image](https://cloud.githubusercontent.com/assets/497926/4270438/33652c8e-3ccb-11e4-9cdf-e641ffbfa6c5.png)

Thanks

**Comment by mbonaci** [comment]
So are we going to fix this?
You can always fork and rename the theme as your own and let me handle mine myself?

Take a look here:
https://atom.io/themes/mbo

**Comment by birdwing** [comment]
Sorry about that, I haven't been able to touch my personal projects in a little bit.
I will get to this sometime soon!

**Comment by birdwing** [comment]
Switched to the first color you posted (white)

**Comment by mbonaci** [comment]
Thanks :+1:
